services:
  # 1. The Database (Message Queue)
  redis:
    image: redis:alpine
    # Ports hidden. Only internal Docker network can access.

  # 2. The API Server (Receives build requests)
  api-server:
    build: ./api-server # Make sure this matches your API folder name
    ports:
      - "9000:9000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  # 3. The Builder (Compiles and Uploads)
  build-server:
    build: ./build-server
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_OPTIONS=--dns-result-order=ipv4first
      # Mapping Oracle credentials to AWS variables to trick the SDK
      - AWS_ACCESS_KEY_ID=${ORC_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${ORC_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${ORC_BUCKET_NAME}
      - AWS_REGION=${ORC_REGION}
      - AWS_ENDPOINT_URL=${ORC_ENDPOINT_URL} 
      - NPM_CONFIG_CACHE=/npm-cache
    depends_on:
      - redis
    volumes:
      - build_cache:/npm-cache

  # 4. The Node.js S3 Proxy (Fetches sites from Oracle S3)
  s3-proxy:
    build: ./s3-reverse-proxy # Make sure this matches your proxy folder name (where index.ts is)
    expose:
      - "8000" # Exposes internally to Nginx, not to the public internet
    environment:
      - AWS_ACCESS_KEY_ID=${ORC_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${ORC_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${ORC_BUCKET_NAME}
      - AWS_REGION=${ORC_REGION}
      - AWS_ENDPOINT_URL=${ORC_ENDPOINT_URL}

  # 5. The Router (Public facing Nginx web server)
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - s3-proxy
volumes:
  build_cache:   

  # 6. Frontend
  frontend:
    build: ./frontend  # Path to your Next.js folder containing its Dockerfile
    restart: always
    expose:
      - "3000" # Standard Next.js port, exposed internally to Nginx  